INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,1,'入庫',1000,TO_DATE('2025/12/31/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,2,'入庫',2000,TO_DATE('2025/12/31/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,3,'入庫',3000,TO_DATE('2025/12/31/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,4,'入庫',4000,TO_DATE('2025/12/31/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,3,'出庫',300,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,4,'出庫',400,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,5,'入庫',5000,TO_DATE('2025/12/31/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,6,'入庫',6000,TO_DATE('2025/12/31/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,5,'出庫',500,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,6,'出庫',600,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,5,'返品',500,TO_DATE('2026/01/02/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,6,'返品',600,TO_DATE('2026/01/02/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,7,'入庫',7000,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,8,'入庫',8000,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,9,'入庫',9000,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,10,'入庫',10000,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,9,'出庫',900,TO_DATE('2026/01/02/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,10,'出庫',1000,TO_DATE('2026/01/02/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,1,'出庫',100,TO_DATE('2026/01/02/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,2,'出庫',200,TO_DATE('2026/01/02/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,1,'返品',100,TO_DATE('2026/01/03/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,2,'返品',200,TO_DATE('2026/01/03/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,5,'出庫',500,TO_DATE('2026/01/03/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,6,'出庫',600,TO_DATE('2026/01/03/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,7,'出庫',700,TO_DATE('2026/01/03/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,8,'出庫',800,TO_DATE('2026/01/03/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,7,'返品',700,TO_DATE('2026/01/04/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,8,'返品',800,TO_DATE('2026/01/04/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,1,'出庫',100,TO_DATE('2026/01/04/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,2,'出庫',200,TO_DATE('2026/01/04/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,3,'出庫',300,TO_DATE('2026/01/04/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,4,'出庫',400,TO_DATE('2026/01/04/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,3,'返品',300,TO_DATE('2026/01/05/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,4,'返品',400,TO_DATE('2026/01/05/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,7,'出庫',700,TO_DATE('2026/01/05/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,8,'出庫',800,TO_DATE('2026/01/05/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,9,'出庫',900,TO_DATE('2026/01/05/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,10,'出庫',1000,TO_DATE('2026/01/05/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,9,'返品',900,TO_DATE('2026/01/06/01','YYYY/MM/DD/HH24')
);

INSERT INTO inventory_history VALUES(
inventory_history_seq.NEXTVAL,10,'返品',1000,TO_DATE('2026/01/06/01','YYYY/MM/DD/HH24')
);