INSERT INTO products VALUES(
product_seq.NEXTVAL,1,'商品A',1000,1000
);

INSERT INTO products VALUES(
product_seq.NEXTVAL,2,'商品B',2000,2000
);

INSERT INTO products VALUES(
product_seq.NEXTVAL,3,'商品C',3000,3000
);

INSERT INTO products VALUES(
product_seq.NEXTVAL,4,'商品D',4000,4000
);

INSERT INTO products VALUES(
product_seq.NEXTVAL,5,'商品E',5000,5000
);

INSERT INTO products VALUES(
product_seq.NEXTVAL,1,'商品F',6000,6000
);

INSERT INTO products VALUES(
product_seq.NEXTVAL,2,'商品G',7000,7000
);

INSERT INTO products VALUES(
product_seq.NEXTVAL,3,'商品H',8000,8000
);

INSERT INTO products VALUES(
product_seq.NEXTVAL,4,'商品I',9000,9000
);

INSERT INTO products VALUES(
product_seq.NEXTVAL,5,'商品J',10000,10000
);