INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24'),'発注中'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24'),'納品済'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/01/01','YYYY/MM/DD/HH24'),'キャンセル'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/02/01','YYYY/MM/DD/HH24'),'発注中'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/02/01','YYYY/MM/DD/HH24'),'納品済'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/02/01','YYYY/MM/DD/HH24'),'キャンセル'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/03/01','YYYY/MM/DD/HH24'),'発注中'
);7

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/03/01','YYYY/MM/DD/HH24'),'納品済'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/03/01','YYYY/MM/DD/HH24'),'キャンセル'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/04/01','YYYY/MM/DD/HH24'),'発注中'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/04/01','YYYY/MM/DD/HH24'),'納品済'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/04/01','YYYY/MM/DD/HH24'),'キャンセル'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/05/01','YYYY/MM/DD/HH24'),'発注中'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/05/01','YYYY/MM/DD/HH24'),'納品済'
);

INSERT INTO purchase_orders VALUES(
po_seq.NEXTVAL,TO_DATE('2026/01/05/01','YYYY/MM/DD/HH24'),'キャンセル'
);