INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,1,1,100
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,1,2,200
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,2,3,300
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,2,4,400
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,3,5,500
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,3,6,600
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,4,7,700
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,4,8,800
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,5,9,900
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,5,10,1000
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,6,1,100
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,6,2,200
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,7,3,300
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,7,4,400
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,8,5,500
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,8,6,600
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,9,7,700
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,9,8,800
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,10,9,900
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,10,10,1000
);
INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,11,1,100
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,11,2,200
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,12,3,300
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,12,4,400
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,13,5,500
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,13,6,600
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,14,7,700
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,14,8,800
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,15,9,900
);

INSERT INTO purchase_order_details　VALUES(
po_detail_seq.NEXTVAL,15,10,1000
);